RuntimeThinkers/devcheatsheet

README.md
- hey check out this updated readmi file
=> fix: updated reame file

README.md
added liscence info into readme.md please merge it
=> Updated Readme.md file 

mysql.md
Adding new cheat sheet of MYSQL
=> creating mysql.md

cpp.md, mysql.md
Updated Cheatsheet with some C++ Basics
=> Updated Cheatsheet with C++ Basics

Python CheatSheet.md
Issue #7  
Created a Python CheatSheet.
=> Create Python CheatSheet.md

Kali_linux.md
=> Kali_linux cheatsheet

cpp.md
Added **Fast Input-Output** code for C++. It helps in **Competitive Programming**.
=> Added Fast Input-Output for Competitive Programming in cpp.md

Markdown.md
=> created markdown.md

shell_scripting.md
Kindly review and merge my PR.
=> Created  a cheatsheet on Shell Scripting

cpp.md
Added random math function **rand()** used to get any random number in the required range in c++.
=> Added random function rand() in cpp 

git.md
Updated formatting and some commands.
=> fix: proper formatting of git.md #35

python.md
=> updated python.md file

cpp.md
Added CheatCode to select complete vector from begin to end and can apply various functions to that.
=> Added select all cheatcode in cpp.md

C++_CheatSheet.md
Added standard header file and pragmas for fast compilation.
=> Added header,pragmas in C++

yaml.md
YAML is a human-friendly data serialization language. This is the most commonly used sytax for configuration files.
=> created yaml.md

solidity.md
Solidity is a statically-typed curly-braces programming language designed for developing smart contracts that run on Ethereum.
=> added Solidity Cheatsheet

java.md
Resolves https://github.com/RuntimeThinkers/devcheatsheet/issues/6
=> feat: add java cheat sheet

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Issue #50 
I have added a CODE OF CONDUCT file and fixed the error in the CONTRIBUTING.md file.
=> Fix contributing.md#50

cpp.md
Please look at the stuff that I have added, hopefully it should help :)
=> Added few more literals

cpp.md
I have added few more things that were needed in the string part
=> added some more stuff to strings

README.md
Fixed some commands in README.
@sahiljawale54
=> fix: README #65

javascript.md
I have added javascript cheatsheet 
pls review it merge it
=> Added javascript cheatsheet

react-three-fibre.md
Added react three fibre cheatsheet for Canvas And Events
=> React three fibre

java.md
Added some important details on data types
=> literals and defaults

flutter.md
Please check the PR if its correct merge it and please marked me as Hacktoberfest-accepted
=> Flutter Cheatsheet Added

python.md
Added some important math functions and multiline comments
=> Added some Points

C++.md
I added the syntax to initialize 2d vectors and a few more functions. Please review it and let me know if any changes are required, thank you!
=> Added some more functions to the vector section in C++ cheatsheet

javascript.md
Hello, I added the scope of variables in the variables section, arrow functions in the functions section and the for-of loop in the loops section. Please consider merging the pull request or asking for changes, if you find it appropriate to do so. Thank you!
=> Adding more info to the Javascript Cheatsheet

php.md
@Sahiljawale @sahiljawale54 
added all the details about php and cheatsheet.
do check the pr and add hacktoberfest label.
=> Added all the details about the "php"

html.md
I have added HTML cheatsheet with the necessary basic syntaxes
=> :art:Added HTML Cheatsheet

NumPy.md
Hacktober 2022
Added Numpy CheatSheet.
=> Added Numpy CheatSheet

node.md
I have made a NODE.JS cheatsheet . I hope this will help the community .
HAPPY CODING : )
=> Added node cheatsheet

css.md
A Cheetsheet For CSS Developers
=> Added CSS Markdown Cheatsheet

vim editor_cheatsheet.md
so that you don't have to panic next time
=> Vim Editor Cheatsheet

vi-emacs-nano.md
added new cheat sheet about command line editors as it is very helpful in development, and everyone should know these.
this cheatsheet contain about vi emacs and nano
=> added new cheatsheet

Kotlin.md
kotlin cheatsheet added.
Hacktoberfest 2022
=> Added Kotlin.md cheatsheet

vectors.cpp
Demonstrating syntax of vectors in C++.
=> Demonstration of vectors

multimap.cpp
Demonstrating syntax for multimaps in C++.
=> Demonstration of Multimaps

map.cpp
Demonstrating syntax for maps in C++
=> Demonstration of maps

set.cpp
Demonstrating syntax for sets in C++.
=> Demonstration of sets

golang.md
Hi @Sahiljawale I have added golang.md for Golang language. Please take a look.
=> Cheatsheet for golang language
